# Example encrypted secrets for Development environment
# This file would be encrypted using SOPS with age encryption

database:
    host: ENC[AES256_GCM,data:XvMhWVQzD3...==,tag:abc123==]
    username: ENC[AES256_GCM,data:YwNi...==,tag:def456==]
    password: ENC[AES256_GCM,data:ZxPk8g...==,tag:ghi789==]
    
spring:
    datasource:
        url: ENC[AES256_GCM,data:jdbc:postgresql://dev-db.internal:5432/nbfc_core,tag:jkl012==]
        
jwt:
    secret: ENC[AES256_GCM,data:Wx5yH8K...==,tag:mno345==]
    expiration: 3600000
    
external:
    apis:
        cibil:
            url: ENC[AES256_GCM,data:https://api.cibil.com/v2,tag:pqr678==]
            key: ENC[AES256_GCM,data:cibil_api_key_dev,tag:stu901==]
        equifax:
            url: ENC[AES256_GCM,data:https://api.equifax.com/v1,tag:vwx234==]
            key: ENC[AES256_GCM,data:equifax_api_key_dev,tag:yzab567==]
            
rbi:
    reporting:
        endpoint: ENC[AES256_GCM,data:https://rbi-reporting-dev.internal,tag:cdef890==]
        api_key: ENC[AES256_GCM,data:rbi_dev_key,tag:ghij123==]

# SOPS metadata (automatically added by SOPS)
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNGk4...
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T10:30:00Z"
    mac: ENC[AES256_GCM,data:abc123def456...,tag:xyz789==]
    pgp: []
    encrypted_regex: ^(password|secret|key|token|api_key)$
    version: 3.8.1