# Example encrypted secrets for UAT environment

database:
    host: ENC[AES256_GCM,data:UATHostEncrypted...==,tag:uat123==]
    username: ENC[AES256_GCM,data:UATUser...==,tag:uat456==]
    password: ENC[AES256_GCM,data:UATPass...==,tag:uat789==]
    
spring:
    datasource:
        url: ENC[AES256_GCM,data:jdbc:postgresql://uat-db.internal:5432/nbfc_core,tag:uat012==]
        
jwt:
    secret: ENC[AES256_GCM,data:UATJWTSecret...==,tag:uat345==]
    expiration: 1800000  # Shorter expiration for UAT
    
external:
    apis:
        cibil:
            url: ENC[AES256_GCM,data:https://api-uat.cibil.com/v2,tag:uat678==]
            key: ENC[AES256_GCM,data:cibil_api_key_uat,tag:uat901==]
        equifax:
            url: ENC[AES256_GCM,data:https://api-uat.equifax.com/v1,tag:uat234==]
            key: ENC[AES256_GCM,data:equifax_api_key_uat,tag:uat567==]
            
rbi:
    reporting:
        endpoint: ENC[AES256_GCM,data:https://rbi-reporting-uat.internal,tag:uat890==]
        api_key: ENC[AES256_GCM,data:rbi_uat_key,tag:uat123==]

sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNGk4...
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T11:30:00Z"
    mac: ENC[AES256_GCM,data:uat123def456...,tag:uat789==]
    pgp: []
    encrypted_regex: ^(password|secret|key|token|api_key)$
    version: 3.8.1